
package cn.WS.WSDL2Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebApp", targetNamespace = "http://WS.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebApp {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://WS.cn/", className = "cn.WS.WSDL2Client.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://WS.cn/", className = "cn.WS.WSDL2Client.SayHiResponse")
    @Action(input = "http://WS.cn/WebApp/sayHiRequest", output = "http://WS.cn/WebApp/sayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
