
package cn.WS.WSDL2Client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebAppService", targetNamespace = "http://WS.cn/", wsdlLocation = "http://localhost:8080/hi?wsdl")
public class WebAppService
    extends Service
{

    private final static URL WEBAPPSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBAPPSERVICE_EXCEPTION;
    private final static QName WEBAPPSERVICE_QNAME = new QName("http://WS.cn/", "WebAppService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBAPPSERVICE_WSDL_LOCATION = url;
        WEBAPPSERVICE_EXCEPTION = e;
    }

    public WebAppService() {
        super(__getWsdlLocation(), WEBAPPSERVICE_QNAME);
    }

    public WebAppService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBAPPSERVICE_QNAME, features);
    }

    public WebAppService(URL wsdlLocation) {
        super(wsdlLocation, WEBAPPSERVICE_QNAME);
    }

    public WebAppService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBAPPSERVICE_QNAME, features);
    }

    public WebAppService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebAppService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebApp
     */
    @WebEndpoint(name = "WebAppPort")
    public WebApp getWebAppPort() {
        return super.getPort(new QName("http://WS.cn/", "WebAppPort"), WebApp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebApp
     */
    @WebEndpoint(name = "WebAppPort")
    public WebApp getWebAppPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WS.cn/", "WebAppPort"), WebApp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBAPPSERVICE_EXCEPTION!= null) {
            throw WEBAPPSERVICE_EXCEPTION;
        }
        return WEBAPPSERVICE_WSDL_LOCATION;
    }

}
